name = "matam/multi_drep_delegation"
version = "0.0.0"
compiler = "v1.1.4"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'matam/multi_drep_delegation'"

[repository]
user = "matam"
project = "multi_drep_delegation"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.0.0"
source = "github"

[config]
